### ISSUE TITLE
update to latest inkv4.1.0

### ISSUE THREAD

**Issue by ganesh1997oli** [pendulum-chain/pendulum-ink-wrapper#1]
are you planning to update latest version?

**Comment by TorstenStueber** [comment]
@ebma is this even relevant anymore? Our wrappers are now written in Solidity and we can probably remove move them out of the main branch (?)

**Comment by ebma** [comment]
I don't think it's relevant anymore. But this is a good indicator that we should restructure the content of this repository (and also rename it overall).

**Comment by TorstenStueber** [comment]
I added a ticket: https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/pendulum-ink-wrapper/38

Can you check whether it makes sense?

**Comment by ebma** [comment]
Makes sense, let's close this ticket then. We will not update the ink version of the contracts then because we decided to replace them with Solang-compiled wrapper contracts.
