### ISSUE TITLE
Make cross-contract communication work using IERC20 interface

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-ink-wrapper#14]
In order to be fully compatible with the ERC-20 interface that existing Solidity contracts expect, we need to make sure that them calling our PSP-22 contract using the [IERC-20 ](https://github.com/pendulum-chain/pendulum-ink-wrapper/blob/8b1291ecb8f99da115c30e250b5254bee7c9fa06/solidity-sample/openzeppelin-contracts/interfaces/IERC20.sol)interface works. This does not seem to be the case at the moment, as all cross-contract calls using this `IERC-20` interface fail. However, some of these functions work when specifying the `hex` value as a selector. This indicates that maybe there is a problem with the interface contract itself.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/14?planning-poker) with Zenhub @ebma @ashneverdawn
