### ISSUE TITLE
Audit: Floating Pragma

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum-ink-wrapper#21]
### Context
Contracts should be deployed with the same compiler version and flags
that they have been tested with thoroughly. Locking the pragma helps
to ensure that contracts do not accidentally get deployed using, for
example, an outdated compiler version that might introduce bugs that
affect the contract system negatively.

### Path:
./price-oracle-wrapper/interfaces/IPriceOracleGetter.sol

### Recommendation: 
it is recommended to lock the pragma version in all
contracts as stated by SWC-103

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/21?planning-poker) with Zenhub @TorstenStueber @ebma @ashneverdawn
