### ISSUE TITLE
The ERC20 wrapper contract does not implement IERC20.

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-ink-wrapper#39]
The ERC20 wrapper contract is currently not an ERC20 smart contract because it does not implement the [IERC20 interface](https://github.com/pendulum-chain/pendulum-ink-wrapper/blob/master/erc20-wrapper/ERC20Wrapper.sol).

For that reason the wrapper contract incorrectly misses to mark the following three functions as view functions:
* `totalSupply`
* `balanceOf`
* `allowance`

The compiled contract then requires to submit these functions as transactions to the chain (instead of just reading them inside an RPC node) and the functions will be unable to return a value (due to the way pallet-contracts works).

This is incorrect. We want to be able to use these functions to read value and just execute them in the RPC node without submitting a transaction and paying transaction fees.

**Comment by TorstenStueber** [comment]
Is there a limit with marking chain extensions as "view only"?

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/39?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
@pendulum-chain/product this ticket is very important for the proper interaction with Nabla and other smart contracts that use our wrapper contracts.

**Comment by TorstenStueber** [comment]
I hit a dead end here

```
error: function declared 'view' but this expression writes to state
   ┌─ /Users/torsten/Development/pendulum/wasm-deploy/target/git/pendulumWrappers/erc20-wrapper/ERC20Wrapper.sol:71:53
   │
71 │         (uint32 result_chain_ext, bytes raw_data) = chain_extension(1101, input);
```

Seems like it is not possible to have viewable chain extensions that we could call into...

**Comment by TorstenStueber** [comment]
Due to the problem above, there is currently no direct solution possible and we are going to implement a workaround instead. For that reason I will close this issue.

**Comment by prayagd** [comment]
@TorstenStueber Can you please add the estimates?

**Comment by TorstenStueber** [comment]
I closed this as completed but meant to close it as not planned.
